### ISSUE TITLE
@notblank validation on input type is not working. Getting below error.

### ISSUE THREAD

**Issue by brendamckenne** [graphql-java/graphql-java-extended-validation#12] opened 2020-04-04 13:04 UTC
**@NotBlank** validation on input type is not working. Getting below error.

Schema is like this:
```
directive @NotBlank(message : String = "graphql.validation.NotBlank.message") on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

type Query {
  group(id: GroupIDInput) : Group
}

input GroupIDInput {
    name: String @NotBlank
}

```

Getting below error:

`
{"errorType":"java.lang.NoSuchMethodError","errorMessage":"graphql.schema.GraphQLInputType.getName()Ljava/lang/String;","stackTrace":["graphql.validation.constraints.AbstractDirectiveConstraint.isOneOfTheseTypes(AbstractDirectiveConstraint.java:167)","graphql.validation.constraints.standard.NotBlankRule.appliesToType(NotBlankRule.java:39)","graphql.validation.constraints.AbstractDirective`

**Comment by setchy** [comment] 2020-09-20 13:21
Closing this as duplicate of #13

**Comment by setchy** [comment] 2020-09-20 13:21
Closing this as duplicate of #13

**Closed by setchy** 2020-09-20 13:21 UTC
