### ISSUE TITLE
Validations doesn't work if input type has exclamation mark (!) which is a way in graphql to mark input as mandatory

### ISSUE THREAD

**Issue by brendamckenne** [graphql-java/graphql-java-extended-validation#13] opened 2020-04-11 11:15 UTC
The validations doesnt work with input types having "**!**" mark (exclamation mark)
below is example schema (note the **!** mark after **GroupIDInput** )
 
```
type Query {
  group(id: GroupIDInput!) : Group
}


input GroupIDInput {
    name: String! @NotBlank
 }
```

In such cases, validations doesn't work at all.The **name: String! @NotBlank** field doesn't get validated even if left blank.

However, if we remove ! mark from GroupIDInput, everything works fine then.

**Comment by setchy** [comment] 2020-09-20 13:23
Closing at duplicate of #17

**Closed by setchy** 2020-09-20 13:23 UTC
